[package]
name = "plaything"
version = "0.1.0"
authors = ["kohelet <kohelet@kohelet.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
